
#the config of mybatis
mybatis:
  mapper-locations: classpath*:/mappers/*.xml

  type-aliases-package: com.ausn.pilipili.entity

mybatis-plus:
  mapper-locations: classpath*:/mappers/*.xml
  type-aliases-package: com.ausn.pilipili.entity


server:
  port: 8080

spring:
  #the config of mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pilipili_db
    username: root
    password: FXYiloveyou1314
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html

  #the config of redis
  redis:
    host: 192.168.107.128
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 1

  jackson:
    default-property-inclusion: non_null

  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB

  #the config of kafka
  kafka:
    bootstrap-servers: 192.168.107.128:9092
    producer:
      batch-size: 32768
      buffer-memory: 33554432
      compression-type: snappy
      acks: 1
      retries: 1

    consumer:
      enable-auto-commit: false

    listener:
      ack-mode: manual

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    com:
      ausn: debug
