
mybatis:
  mapper-locations: classpath*:/mappers/*.xml

  type-aliases-package: com.ausn.pilipili.entity

server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pilipili_db
    username: root
    password: FXYiloveyou1314


  thymeleaf:
    prefix: classpath:/static/
    suffix: .html

  redis:
    host: 192.168.107.128
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 1

  jackson:
    default-property-inclusion: non_null

logging:
  level:
    com:
      ausn: debug